# Site settings
title: Sitarist
email: akshatamotilalsa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The sitar is a plucked stringed instrument, originating from the Indian subcontinent, used in Hindustani classical music. The instrument flourished under the Mughals, and it is named after a Persian instrument called the setar..
baseurl: "/akshata" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
